/********************************************************************
* SimpleTableDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error SimpleTableDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableSimpleTableDict();
extern void G__cpp_setup_inheritanceSimpleTableDict();
extern void G__cpp_setup_typetableSimpleTableDict();
extern void G__cpp_setup_memvarSimpleTableDict();
extern void G__cpp_setup_globalSimpleTableDict();
extern void G__cpp_setup_memfuncSimpleTableDict();
extern void G__cpp_setup_funcSimpleTableDict();
extern void G__set_cpp_environmentSimpleTableDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "CTable.h"
#include "CNumBase.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__SimpleTableDictLN_TString;
extern G__linked_taginfo G__SimpleTableDictLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__SimpleTableDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SimpleTableDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__SimpleTableDictLN_string;
extern G__linked_taginfo G__SimpleTableDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__SimpleTableDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimpleTableDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__SimpleTableDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimpleTableDictLN_CTableCellSetter;
extern G__linked_taginfo G__SimpleTableDictLN_CTableColumnLabeler;
extern G__linked_taginfo G__SimpleTableDictLN_CTable;
extern G__linked_taginfo G__SimpleTableDictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__SimpleTableDictLN_vectorlEstringcOallocatorlEstringgRsPgRcLcLiterator;
extern G__linked_taginfo G__SimpleTableDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimpleTableDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR;
extern G__linked_taginfo G__SimpleTableDictLN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__SimpleTableDictLN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__SimpleTableDictLN_CNumBaselEfloatgR;
extern G__linked_taginfo G__SimpleTableDictLN_CNumBaselEdoublegR;

/* STUB derived class for protected member access */
typedef vector<string,allocator<string> > G__vectorlEstringcOallocatorlEstringgRsPgR;
typedef vector<vector<string,allocator<string> >,allocator<vector<string,allocator<string> > > > G__vectorlEvectorlEstringcOallocatorlEstringgRsPgRcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRsPgRsPgR;
typedef CNumBase<float> G__CNumBaselEfloatgR;
typedef CNumBase<double> G__CNumBaselEdoublegR;
